export const baseTheme = {
  "font-sans": '"Inter", ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  "font-mono": "\"Geist Mono\", 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', '\"Liberation Mono\"', '\"Courier New\"', 'monospace'",
  "font-sans--font-feature-settings": '"cv02", "cv03", "cv04", "cv11"',
  "font-mono--font-feature-settings": '"ss02", "zero"',
  "color-border": "var(--border)",
  "color-input": "var(--input)",
  "color-ring": "var(--ring)",
  "color-bg": "var(--bg)",
  "color-fg": "var(--fg)",
  "color-primary": "var(--primary)",
  "color-primary-fg": "var(--primary-fg)",
  "color-primary-subtle": "var(--primary-subtle)",
  "color-primary-subtle-fg": "var(--primary-subtle-fg)",
  "color-secondary": "var(--secondary)",
  "color-secondary-fg": "var(--secondary-fg)",
  "color-accent": "var(--accent)",
  "color-accent-fg": "var(--accent-fg)",
  "color-success": "var(--success)",
  "color-success-fg": "var(--success-fg)",
  "color-success-subtle": "var(--success-subtle)",
  "color-success-subtle-fg": "var(--success-subtle-fg)",
  "color-danger": "var(--danger)",
  "color-danger-fg": "var(--danger-fg)",
  "color-danger-subtle": "var(--danger-subtle)",
  "color-danger-subtle-fg": "var(--danger-subtle-fg)",
  "color-warning": "var(--warning)",
  "color-warning-fg": "var(--warning-fg)",
  "color-warning-subtle": "var(--warning-subtle)",
  "color-warning-subtle-fg": "var(--warning-subtle-fg)",
  "color-info-subtle": "var(--info-subtle)",
  "color-info-subtle-fg": "var(--info-subtle-fg)",
  "color-muted": "var(--muted)",
  "color-muted-fg": "var(--muted-fg)",
  "color-overlay": "var(--overlay)",
  "color-overlay-fg": "var(--overlay-fg)",
  "color-navbar": "var(--navbar)",
  "color-navbar-fg": "var(--navbar-fg)",
  "color-sidebar": "var(--sidebar)",
  "color-sidebar-fg": "var(--sidebar-fg)",
  "color-sidebar-primary": "var(--sidebar-primary)",
  "color-sidebar-primary-fg": "var(--sidebar-primary-fg)",
  "color-sidebar-accent": "var(--sidebar-accent)",
  "color-sidebar-accent-fg": "var(--sidebar-accent-fg)",
  "color-sidebar-border": "var(--sidebar-border)",
  "color-sidebar-ring": "var(--sidebar-ring)",
  "color-chart-1": "var(--chart-1)",
  "color-chart-2": "var(--chart-2)",
  "color-chart-3": "var(--chart-3)",
  "color-chart-4": "var(--chart-4)",
  "color-chart-5": "var(--chart-5)",
  "radius-xs": "var(--radius-xs)",
  "radius-sm": "var(--radius-sm)",
  "radius-md": "var(--radius-md)",
  "radius-lg": "var(--radius-lg)",
  "radius-xl": "var(--radius-xl)",
  "radius-2xl": "var(--radius-2xl)",
  "radius-3xl": "var(--radius-3xl)",
  "radius-4xl": "var(--radius-4xl)",
}
